import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image 
        src="/img/pb.png"
        alt="a"
        width={500}
        height={500}
        />
        <h1 className={styles.title}>
          Agus Dustin <br />
          Sudarta
        </h1>
      </main>
    </div>
  );
}
